list=[]
print("empty list:")
list.append(10)
list.append(20)
list.append('rv')
print("\nAfter appending data :")
print(list)
list.insert(2,'engineer')
print("\n after inserting data :")
print(list)
list.extend([50,60,"singh"])
print("\n after extending data :")
print(list)